name: Build Ubuntu 20.04

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Cap’n Proto
      run: |
        mkdir "${{ runner.workspace }}/capnp"
        cd "${{ runner.workspace }}/capnp"
        curl -O https://capnproto.org/capnproto-c++-0.8.0.tar.gz
        tar zxf capnproto-c++-0.8.0.tar.gz
        cd capnproto-c++-0.8.0
        ./configure
        make -j
        sudo make install
